#!/bin/sh

mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

echo "Dropping you."
#echo "Dropping you,"
#ls
#echo "Dropping you to a shell"
#sleep 10
echo "Alive" > /dev/ttySAC0
exec /bin/ash
exec /bin/sh </dev/ttySAC0 >/dev/ttySAC0 2>/dev/ttySAC0
